### ISSUE TITLE
Button overlay

### ISSUE THREAD

**Issue by zebrik** [hal/console#158]
See [screenshot](https://issues.jboss.org/secure/attachment/12429510/Screenshot-2018-1-4%20HAL%20Management%20Console.png)
In the upper right corner, you can see Remove button overlayed by some flash (?) button.
The browser was Firefox 57.0.3 on Ubuntu 16.04. 
HAL.Next was 0.9.4-SNAPSHOT build from 2017-01-03.
JIra https://issues.jboss.org/browse/HAL-1388 already created.

**Comment by hpehl** [comment]
Seems to be related to the copy-to-clipboard JS lib.

**Comment by hpehl** [comment]
Moved to https://issues.jboss.org/browse/HAL-1412
