### ISSUE TITLE
Host view doesn't show attributes

### ISSUE THREAD

**Issue by claudio4j** [hal/console#178]
Host view in domain mode, doesn't show the attributes of /host=*, this is wrong because there are lots of attributes there.

**Comment by claudio4j** [comment]
I was able to reproduce it, by start wildfly in domain mode bind to localhost, load the host view, then stop, start domain mode with binding to a valid IP address, the load the host view, there is a "TypeError: Cannot read property 'NY' of null". To workaround, clean the browser storage.

**Comment by hpehl** [comment]
Could you figure out where exactly the code fails?

**Comment by hpehl** [comment]
Moved to https://issues.jboss.org/browse/HAL-1403
