### ISSUE TITLE
Text filtering on log files

### ISSUE THREAD

**Issue by ggam** [hal/console#68]
Hi guys, great job so far!

The new log view is really improved. One thing I'd really like to see is text filtering, apart from the search that's already there. Filtering would work like grep, showing only lines containing the given text.

This would also workaound [HAL-1064](https://issues.jboss.org/browse/HAL-1064)

**Comment by hpehl** [comment]
Makes sense to me. Need to check if this works on large log files.

**Comment by hpehl** [comment]
Moved to https://issues.jboss.org/browse/HAL-1429
