### ISSUE TITLE
Show resource attribute help on top of its respective target attribute

### ISSUE THREAD

**Issue by ggam** [hal/console#72]
The help box that's present on every page is really useful but when there are a lot of attributes (example: EJB3 subsystem), just the help box occupies more than the whole screen, forcing the user to do Ctrl+F to search for the attribute.

I think it would be simpler to see the description just on top (or aside) of each attribute.

Example screenshots showing the problem:

EJB3 attributes:
![ejb3 attributes](https://cloud.githubusercontent.com/assets/2109040/22618158/fd0ea0e6-ead5-11e6-9795-8e1223a4ad05.png)

EJB3 help box:
![ejb3 help](https://cloud.githubusercontent.com/assets/2109040/22618160/009a2122-ead6-11e6-8781-fcd16b8be47e.png)

**Comment by hpehl** [comment]
I see your point. On the other hand for big forms - like for the EJB subsystem - you'd need a help icon, link or some other indicator (see [1]). This would introduce pretty much 'noise' to the UI. So I opt for keeping the help as it is.

**Comment by ggam** [comment]
Sorry, I don't get you. My idea was to keep the Help icon where it is, but move the messages to the corresponding field, like a validation error. Not sure how well would that work.

**Comment by hpehl** [comment]
So you would stick with the one help link above the form, but would like to show the help text below each field? Hmm need to test this with a prototype.

**Comment by ggam** [comment]
Exactly that! Although It may interfere with validation messages when errors occur, I think it's worth a try.

**Comment by hpehl** [comment]
Moved to https://issues.jboss.org/browse/HAL-1428
