### ISSUE TITLE
Deployment with persistence.xml - check if data source is available

### ISSUE THREAD

**Issue by rsvoboda** [hal/console#95]
When user is deploying application with defined persistence.xml it would be nice to check if defined data source is available. 

Inform user when DS is not available so he/she can take some actions.

By informing I mean to show DS name which is not available and the list of available ones on the server.
This is equivalent of  https://issues.jboss.org/browse/JBEAP-10713 for hal.next

**Comment by hpehl** [comment]
As a first step the failure description of failed operations are now pretty printed:

![screen shot 2017-10-12 at 20 12 42](https://user-images.githubusercontent.com/100611/31512072-fc0d7216-af89-11e7-931e-e99e216613ed.png)

**Comment by rsvoboda** [comment]
:thumbsup:

**Comment by hpehl** [comment]
Moved to https://issues.jboss.org/browse/HAL-1425
